name: Scratch News Bot

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install scratchattach

      - env:
          SCRATCH_SESSION_ID: ${{ secrets.SCRATCH_SESSION_ID }}
          SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }}
        run: python bot.py
