name: Time Bot Test

on:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install scratchattach

      - env:
          SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }}
          SCRATCH_PASSWORD: ${{ secrets.SCRATCH_PASSWORD }}
        run: python bot.py
